// Writes assets/js/config.js from environment variables (or a local .env file)
// and copies the Supabase browser client into assets/vendor/.
//
// Only the project URL and the public (anon / publishable) key are ever written.
// A secret or service_role key is refused: everything in assets/ is downloadable
// by any visitor.
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function readDotEnv(file) {
  const values = {};
  if (!existsSync(file)) return values;
  for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const match = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/.exec(line);
    if (!match || line.trim().startsWith('#')) continue;
    values[match[1]] = match[2].replace(/^(['"])(.*)\1$/, '$2');
  }
  return values;
}

// Real environment variables (hosting dashboards, CI) win over the local .env file.
const env = { ...readDotEnv(join(root, '.env')), ...process.env };
const supabaseUrl = (env.SUPABASE_URL || '').trim().replace(/\/+$/, '');
const supabaseAnonKey = (env.SUPABASE_ANON_KEY || '').trim();

function fail(message) {
  console.error(`\n[config] ${message}\n`);
  process.exit(1);
}

function jwtRole(key) {
  try {
    return JSON.parse(Buffer.from(key.split('.')[1], 'base64url').toString('utf8')).role || '';
  } catch {
    return '';
  }
}

if (env.SUPABASE_SERVICE_ROLE_KEY || env.SUPABASE_SECRET_KEY) {
  console.warn('[config] Ignoring SUPABASE_SERVICE_ROLE_KEY / SUPABASE_SECRET_KEY – this site never uses a secret key.');
}
if (supabaseAnonKey.startsWith('sb_secret_') || jwtRole(supabaseAnonKey) === 'service_role') {
  fail('SUPABASE_ANON_KEY contains a secret / service_role key. Use the public "anon" (or "publishable") key instead – a secret key in browser code would give every visitor full database access.');
}
if (supabaseUrl && !/^https?:\/\/[^\s/]+$/.test(supabaseUrl)) {
  fail(`SUPABASE_URL does not look like a project URL (expected e.g. https://abcdefgh.supabase.co), got: ${supabaseUrl}`);
}
if (Boolean(supabaseUrl) !== Boolean(supabaseAnonKey)) {
  fail('Set both SUPABASE_URL and SUPABASE_ANON_KEY, or neither.');
}

const configured = Boolean(supabaseUrl && supabaseAnonKey);
const config = { supabaseUrl, supabaseAnonKey };

writeFileSync(
  join(root, 'assets/js/config.js'),
  '// Generated by scripts/build-config.mjs from environment variables – do not edit or commit.\n' +
    `window.CAGE_SPORTS_CONFIG = ${JSON.stringify(config, null, 2)};\n`
);

const vendorSource = join(root, 'node_modules/@supabase/supabase-js/dist/umd/supabase.js');
if (existsSync(vendorSource)) {
  mkdirSync(join(root, 'assets/vendor'), { recursive: true });
  copyFileSync(vendorSource, join(root, 'assets/vendor/supabase.js'));
} else if (!existsSync(join(root, 'assets/vendor/supabase.js'))) {
  fail('assets/vendor/supabase.js is missing. Run `npm install` first.');
}

console.log(
  configured
    ? `[config] assets/js/config.js written for ${supabaseUrl}`
    : '[config] SUPABASE_URL / SUPABASE_ANON_KEY are not set – assets/js/config.js written WITHOUT a backend. ' +
        'Booking requests cannot be saved until they are set (see README.md).'
);
